FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir boto3 fastapi uvicorn pydantic opensearch-py && \
    pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir sentence-transformers

EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]